# Site settings
author: Jessica H
title: Ctrl Blog
header-img: img/home-bg.png
email: jessicahong.ngnr@gmail.com
copyright_name: Jessica H
description: > # this means to ignore newlines until "baseurl:"
  CB on Ruby and JavaScripts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Hongj2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
